args: !!python/object:argparse.Namespace
  activation_bw: 1
  activation_round: nearest
  batch_size: 128
  checkpoint_path: null
  error_bw: 1
  error_round: nearest
  gradient_bw: 1
  gradient_round: nearest
  learning_rate: 0.1
  mix_precision: true
  momentum: 0.0
  weight_bw: 1
  weight_round: nearest
