args: !!python/object:argparse.Namespace
  activation_bw: 3
  activation_ew: 3
  activation_round: nearest
  batch_size: 64
  check_number_ranges: false
  checkpoint_path: null
  clip: 0.1
  epochs: 200
  error_bw: 3
  error_ew: 3
  error_round: nearest
  gradient_bw: 3
  gradient_ew: 3
  gradient_round: nearest
  learning_rate: 0.1
  log_path: e4m3_log_1_clip
  loss_scale: 2000
  mix_precision: true
  momentum: 0.0
  seed: 1
  weight_bw: 3
  weight_ew: 3
  weight_round: nearest
