args: !!python/object:argparse.Namespace
  activation_bw: 3
  activation_ew: 3
  activation_round: stochastic
  batch_size: 64
  check_number_ranges: false
  checkpoint_path: null
  clip: 1.0
  epochs: 200
  error_bw: 3
  error_ew: 3
  error_round: stochastic
  gradient_bw: 3
  gradient_ew: 3
  gradient_round: stochastic
  learning_rate: 0.1
  log_path: e4m3_log_2_clip
  loss_scale: 6000
  mix_precision: true
  momentum: 0.0
  seed: 2
  weight_bw: 3
  weight_ew: 3
  weight_round: stochastic
