args: !!python/object:argparse.Namespace
  activation_bw: 3
  activation_ew: 3
  activation_round: stochastic
  batch_size: 64
  checkpoint_path: null
  epochs: 200
  error_bw: 3
  error_ew: 3
  error_round: stochastic
  gradient_bw: 3
  gradient_ew: 3
  gradient_round: stochastic
  learning_rate: 0.1
  log_path: e3m3_momentum_log
  loss_scale: 4096
  mix_precision: true
  momentum: 0.9
  weight_bw: 3
  weight_ew: 3
  weight_round: stochastic
