args: !!python/object:argparse.Namespace
  activation_bw: 3
  activation_ew: 4
  activation_round: nearest
  batch_size: 64
  batchnorm: id
  check_number_ranges: false
  checkpoint_path: null
  clip: 100000000000000.0
  epochs: 200
  error_bw: 3
  error_ew: 4
  error_round: nearest
  gradient_bw: 3
  gradient_ew: 2
  gradient_round: nearest
  learning_rate: 0.1
  log_path: results_new_batchnorm_2/f2_b4_log_0_clip
  loss_scale: 1
  mix_precision: true
  momentum: 0.0
  seed: 0
  weight_bw: 3
  weight_ew: 2
  weight_round: nearest
