args: !!python/object:argparse.Namespace
  activation_bw: 1
  activation_round: stochastic
  batch_size: 8
  checkpoint_path: null
  error_bw: 1
  error_round: stochastic
  gradient_bw: 1
  gradient_round: stochastic
  learning_rate: 0.05
  mix_precision: true
  momentum: 0.0
  weight_bw: 1
  weight_round: stochastic
