args: !!python/object:argparse.Namespace
  activation_bw: 5
  activation_round: nearest
  batch_size: 64
  checkpoint_path: null
  epochs: 150
  error_bw: 5
  error_round: nearest
  gradient_bw: 5
  gradient_round: nearest
  learning_rate: 0.1
  log_path: sr_at_diff_stage
  mix_precision: false
  momentum: 0.0
  weight_bw: 5
  weight_round: stochastic
